name: For each commit and PR
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Deps
        run: |
          npm install --global hyperlink@5.0.4
          pip install poetry

          # Install gnome-keyring to get around a funky dependency.
          # https://github.com/Foundry376/Mailspring/issues/681
          sudo apt-get install gnome-keyring

      - name: Run Checks
        run: make test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Deps
        run: |
          pip install poetry

          # Install gnome-keyring to get around a funky dependency.
          # https://github.com/Foundry376/Mailspring/issues/681
          sudo apt-get install gnome-keyring

      - name: Build the site
        run: make build
